CREATE TABLE IF NOT EXISTS "users" (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, username TEXT NOT NULL, hash TEXT NOT NULL);
CREATE UNIQUE INDEX username ON users (username);
CREATE TABLE users_input (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, uid INTEGER NOT NULL, app_name TEXT NOT NULL, app_type TEXT NOT NULL, amount INTEGER NOT NULL, power_usage INTEGER NOT NULL, usage_per_day INTEGER NOT NULL, power_factor REAL NOT NULL);
CREATE TABLE users_personalize (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, uid INTEGER NOT NULL, charge_rate INTEGER, location TEXT, UNIQUE(uid));
